application:
  name: confluence
  createNamespace: ###ZARF_VAR_CONFLUENCE_CREATE_NAMESPACE###
  namespace: confluence
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/community/confluence.git
  ref:
    # renovate: datasource=gitlab-tags depName=big-bang/product/community/confluence versioning=loose registryUrl=https://repo1.dso.mil
    tag: 1.17.1-bb.0
  values: |
    ###ZARF_VAR_CONFLUENCE_VALUES###
  dependsOn:
    ###ZARF_VAR_CONFLUENCE_DEPENDS_ON###
  baseValues:
    proxyName: confluence.###ZARF_VAR_DOMAIN###
    hostname: ###ZARF_VAR_DOMAIN###
    ingress:
      nginx: false
    istio:
      enabled: true
      gateways:
        - istio-system/tenant

    # When istio injected, add an annotation with the istio version to the manager pods only
    podAnnotations:
      bigbang.dev/istioVersion: ###ZARF_VAR_ISTIO_VERSION###

    #Turn off collaborative editing
    synchrony:
      enabled: false

    confluence:
      resources:
        container:
          requests:
            cpu: "100m"
            memory: "1Mi" # demo value
            # memory: "6Gi" # recommended production value
          limits:
            cpu: "10"
            memory: "6Gi"
        jvm:
          maxHeap: "3g"

      additionalEnvironmentVariables:
        - name: ATL_DB_TYPE
          value: "postgresql"
        - name: ATL_DB_DRIVER
          value: "org.postgresql.Driver"
        - name: ATL_JDBC_URL
          value: "jdbc:postgresql://confluence-postgres.confluence.svc.cluster.local:5432/###ZARF_VAR_CONFLUENCE_DB_NAME###"
        - name: ATL_JDBC_USER
          value: ###ZARF_VAR_CONFLUENCE_DB_USERNAME###
        - name: ATL_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "confluence-postgres"
              key: "password"

      localHome:
        persistentVolumeClaim:
          create: true
          # storageClassName: your-storage-class-here
          resources:
            requests:
              storage: 1Gi

    networkPolicies:
      enabled: true
      ingressLabels:
        app: tenant-ingressgateway
      controlPlaneCidr: 0.0.0.0/0
