proxyName: confluence.bigbang.dev
hostname: bigbang.dev
ingress:
  nginx: false
istio:
  enabled: true
  gateways:
    - istio-system/tenant

#Turn off collaborative editing
synchrony:
  enabled: false

confluence:
  resources:
    container:
      requests:
        cpu: "100m"
        memory: "1Mi" # demo value
        # memory: "6Gi" # recommended production value
      limits:
        cpu: "10"
        memory: "6Gi"
    jvm:
      maxHeap: "3g"
  localHome:
    persistentVolumeClaim:
      create: true
      # storageClassName: your-storage-class-here
      resources:
        requests:
          storage: 1Gi
