apiVersion: v1
kind: Secret
metadata:
  name: confluence-postgres
  namespace: confluence
type: kubernetes.io/opaque
stringData:
  username: "###ZARF_VAR_POSTGRES_DB_USERNAME###"
  password: "###ZARF_VAR_POSTGRES_DB_PASSWORD###"
